#!/usr/bin/env node
global.it = require('./src/it.js');
var arg;
if( arg = process.argv[2]) {
  if (arg[0] !== '/') arg = './' + arg;
  require(arg);
}
else {
  console.log('Usage: it your-test.js');
}